"""Added field render_template_uuid to OpenCase

Revision ID: 08dcf7348fba
Revises: 9a4196596c82
Create Date: 2022-07-28 13:03:45.828881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08dcf7348fba'
down_revision = '9a4196596c82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_cases', sa.Column('render_template_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'open_cases', 'render_templates', ['render_template_uuid'], ['uuid'])
    op.create_unique_constraint(None, 'render_templates', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'render_templates', type_='unique')
    op.drop_constraint(None, 'open_cases', type_='foreignkey')
    op.drop_column('open_cases', 'render_template_uuid')
    # ### end Alembic commands ###
