"""Alter OpenCase model

Revision ID: 17b099ec4f77
Revises: a9a2468d307e
Create Date: 2022-07-26 20:59:15.351730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b099ec4f77'
down_revision = 'a9a2468d307e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'open_cases', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'open_cases', type_='unique')
    # ### end Alembic commands ###
