"""Alter OpenCase model

Revision ID: 31e65c55aeb6
Revises: 17b099ec4f77
Create Date: 2022-07-26 21:00:28.213402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e65c55aeb6'
down_revision = '17b099ec4f77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
