"""Alter render_template model

Revision ID: 9a4196596c82
Revises: 31e65c55aeb6
Create Date: 2022-07-28 00:42:57.372139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a4196596c82'
down_revision = '31e65c55aeb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('render_templates',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('html_text', sa.Text(), nullable=True),
    sa.Column('script_text', sa.Text(), nullable=True),
    sa.Column('style_text', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_render_templates_profile_id'), 'render_templates', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_render_templates_profile_id'), table_name='render_templates')
    op.drop_table('render_templates')
    # ### end Alembic commands ###
