"""Added User and OpenCase models

Revision ID: a9a2468d307e
Revises: c8d2bda67132
Create Date: 2022-07-26 01:15:02.098060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9a2468d307e'
down_revision = 'c8d2bda67132'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_cases',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_open_cases_profile_id'), 'open_cases', ['profile_id'], unique=False)
    op.create_table('users',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_users_profile_id'), 'users', ['profile_id'], unique=True)
    op.drop_index('ix_observed_profiles_profile_id', table_name='observed_profiles')
    op.drop_table('observed_profiles')
    op.add_column('items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('open_case_uuid', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'items', 'open_cases', ['open_case_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'open_case_uuid')
    op.drop_column('items', 'created_at')
    op.create_table('observed_profiles',
    sa.Column('profile_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('last_asset_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_observed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('total_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('profile_id', name='observed_profiles_pkey')
    )
    op.create_index('ix_observed_profiles_profile_id', 'observed_profiles', ['profile_id'], unique=False)
    op.drop_index(op.f('ix_users_profile_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_open_cases_profile_id'), table_name='open_cases')
    op.drop_table('open_cases')
    # ### end Alembic commands ###
