"""Alter Price type

Revision ID: c8d2bda67132
Revises: feedd99c7de0
Create Date: 2022-07-22 18:45:38.009467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d2bda67132'
down_revision = 'feedd99c7de0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
